### ISSUE TITLE
Add "Related Section" rules

### ISSUE THREAD

**Issue by rain1024** [rain1024/datastructures-algorithms-competitive-programming#7]
Considering two interesting rules

```yml
# Section "Related Articles"
- name: Content must have "Related Articles" section
  type: regex
  search: "## 🔗 Related Articles\n"
- name: Section "Related Articles" should contains at least 3 items
  type: regex
  search: "## 🔗 Related Articles\n\n(.*\n){3,}"
```
